import { SYSTEM_PROXY_ENV_NAMES } from '@shared/system-proxy'

const UNSET_NAMES = SYSTEM_PROXY_ENV_NAMES.join(' ')

export function buildBashLikeSystemProxyFunctions(names: { proxyOn: string; proxyOff: string; proxyStatus: string }): string {
  const statusLines = SYSTEM_PROXY_ENV_NAMES.map(
    (key) => `  printf '%-12s %s\\n' '${key}' "\${${key}:-(empty)}"`
  ).join('\n')

  return [
    '',
    '_rcland_read_os_proxy() {',
    '  case "$(uname -s)" in',
    '    Darwin)',
    '      local output',
    '      output="$(scutil --proxy 2>/dev/null)" || return',
    '      local enabled host port',
    '      enabled="$(echo "$output" | awk \'/HTTPEnable/ { print $3 }\')"',
    '      host="$(echo "$output" | awk \'/HTTPProxy/ { print $3 }\')"',
    '      if [[ "$enabled" == "1" && -n "$host" ]]; then',
    '        port="$(echo "$output" | awk \'/HTTPPort/ { print $3 }\')"',
    '        echo "http_proxy=http://${host}${port:+:$port}"',
    '        echo "HTTP_PROXY=http://${host}${port:+:$port}"',
    '      fi',
    '      enabled="$(echo "$output" | awk \'/HTTPSEnable/ { print $3 }\')"',
    '      host="$(echo "$output" | awk \'/HTTPSProxy/ { print $3 }\')"',
    '      if [[ "$enabled" == "1" && -n "$host" ]]; then',
    '        port="$(echo "$output" | awk \'/HTTPSPort/ { print $3 }\')"',
    '        echo "https_proxy=http://${host}${port:+:$port}"',
    '        echo "HTTPS_PROXY=http://${host}${port:+:$port}"',
    '      fi',
    '      enabled="$(echo "$output" | awk \'/SOCKSEnable/ { print $3 }\')"',
    '      host="$(echo "$output" | awk \'/SOCKSProxy/ { print $3 }\')"',
    '      if [[ "$enabled" == "1" && -n "$host" ]]; then',
    '        port="$(echo "$output" | awk \'/SOCKSPort/ { print $3 }\')"',
    '        echo "all_proxy=socks5://${host}${port:+:$port}"',
    '        echo "ALL_PROXY=socks5://${host}${port:+:$port}"',
    '      fi',
    '      ;;',
    '    Linux)',
    '      local mode',
    '      mode="$(gsettings get org.gnome.system.proxy mode 2>/dev/null)" || return',
    '      if [[ "$mode" == *"\'manual\'"* ]]; then',
    '        local h p',
    '        h="$(gsettings get org.gnome.system.proxy.http host 2>/dev/null | tr -d "\'")"',
    '        p="$(gsettings get org.gnome.system.proxy.http port 2>/dev/null | tr -d "\'")"',
    '        if [[ -n "$h" && "$h" != "none" ]]; then',
    '          echo "http_proxy=http://${h}${p:+:$p}"',
    '          echo "HTTP_PROXY=http://${h}${p:+:$p}"',
    '        fi',
    '        h="$(gsettings get org.gnome.system.proxy.https host 2>/dev/null | tr -d "\'")"',
    '        p="$(gsettings get org.gnome.system.proxy.https port 2>/dev/null | tr -d "\'")"',
    '        if [[ -n "$h" && "$h" != "none" ]]; then',
    '          echo "https_proxy=http://${h}${p:+:$p}"',
    '          echo "HTTPS_PROXY=http://${h}${p:+:$p}"',
    '        fi',
    '        h="$(gsettings get org.gnome.system.proxy.socks host 2>/dev/null | tr -d "\'")"',
    '        p="$(gsettings get org.gnome.system.proxy.socks port 2>/dev/null | tr -d "\'")"',
    '        if [[ -n "$h" && "$h" != "none" ]]; then',
    '          echo "all_proxy=socks5://${h}${p:+:$p}"',
    '          echo "ALL_PROXY=socks5://${h}${p:+:$p}"',
    '        fi',
    '      fi',
    '      ;;',
    '  esac',
    '}',
    '',
    `${names.proxyOn}() {`,
    '  local lines',
    '  lines="$(_rcland_read_os_proxy)"',
    '  if [[ -z "$lines" ]]; then',
    '    echo "No system proxy detected" >&2',
    '    return 1',
    '  fi',
    '  while IFS= read -r line; do',
    '    [[ -z "$line" ]] && continue',
    '    export "$line"',
    '  done <<< "$lines"',
    '}',
    '',
    `${names.proxyOff}() {`,
    `  unset ${UNSET_NAMES}`,
    '}',
    '',
    `${names.proxyStatus}() {`,
    '  echo "=== OS Proxy ==="',
    '  _rcland_read_os_proxy || echo "(none)"',
    '  echo ""',
    '  echo "=== Current Env ==="',
    statusLines,
    '}',
  ].join('\n')
}

export function buildPowerShellSystemProxyFunctions(names: { proxyOn: string; proxyOff: string; proxyStatus: string }): string {
  const offLines = SYSTEM_PROXY_ENV_NAMES.map(
    (key) => `    Remove-Item "Env:${key}" -ErrorAction SilentlyContinue`
  ).join('\n')

  const envStatusLines = SYSTEM_PROXY_ENV_NAMES.map((key) => {
    const padded = key.padEnd(12, ' ')
    return [
      `    $value = $env:${key}`,
      '    if ([string]::IsNullOrEmpty($value)) { $value = "(empty)" }',
      `    Write-Host ("${padded}: " + $value)`,
    ].join('\n')
  }).join('\n')

  // PowerShell hashtables are case-insensitive, so use lowercase keys only
  // and set both cases when applying
  return [
    '',
    'function _rcland_ReadOsProxy {',
    "  $regPath = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings'",
    '  $enabled = Get-ItemProperty -Path $regPath -Name ProxyEnable -ErrorAction SilentlyContinue',
    '  if ($null -eq $enabled -or $enabled.ProxyEnable -ne 1) {',
    '    return',
    '  }',
    '  $server = (Get-ItemProperty -Path $regPath -Name ProxyServer -ErrorAction SilentlyContinue).ProxyServer',
    '  if ([string]::IsNullOrEmpty($server)) { return }',
    '',
    "  if ($server -notmatch '://') {",
    '    $server = "http://$server"',
    '  }',
    '  @{',
    '    http_proxy  = $server',
    '    https_proxy = $server',
    '  }',
    '}',
    '',
    `function ${names.proxyOn} {`,
    '  $entries = _rcland_ReadOsProxy',
    '  if ($null -eq $entries) {',
    '    Write-Error "No system proxy detected"',
    '    return',
    '  }',
    '  foreach ($key in $entries.Keys) {',
    '    $val = $entries[$key]',
    '    Set-Item "Env:$key" $val',
    '    Set-Item "Env:$($key.ToUpper())" $val',
    '  }',
    '}',
    '',
    `function ${names.proxyOff} {`,
    offLines,
    '}',
    '',
    `function ${names.proxyStatus} {`,
    '  Write-Host "=== OS Proxy ==="',
    '  $entries = _rcland_ReadOsProxy',
    '  if ($null -eq $entries) {',
    '    Write-Host "(none)"',
    '  } else {',
    '    foreach ($key in $entries.Keys) {',
    '      Write-Host ("  $key = " + $entries[$key])',
    '    }',
    '  }',
    '  Write-Host ""',
    '  Write-Host "=== Current Env ==="',
    envStatusLines,
    '}',
  ].join('\n')
}
