import type { ShellType } from '../../../shared/shell'
import type { SectionGenerator } from './section-types'
import type { GenerateContext } from './section-types'
import type { ShellConfigData } from '../../../shared/shell-types'
import type { CCLaunchData } from '../../../shared/types'
import type { CClandSectionData } from './sections/ccland/zsh'

// Section generators
import { VariablesZshGenerator } from './sections/variables/zsh'
import { VariablesBashGenerator } from './sections/variables/bash'
import { VariablesPowerShellGenerator } from './sections/variables/powershell'
import { PathZshGenerator } from './sections/path/zsh'
import { PathBashGenerator } from './sections/path/bash'
import { PathPowerShellGenerator } from './sections/path/powershell'
import { FunctionsZshGenerator } from './sections/functions/zsh'
import { FunctionsBashGenerator } from './sections/functions/bash'
import { FunctionsPowerShellGenerator } from './sections/functions/powershell'
import { AliasesZshGenerator } from './sections/aliases/zsh'
import { AliasesBashGenerator } from './sections/aliases/bash'
import { AliasesPowerShellGenerator } from './sections/aliases/powershell'
import { PromptZshGenerator } from './sections/prompt/zsh'
import { PromptBashGenerator } from './sections/prompt/bash'
import { PromptPowerShellGenerator } from './sections/prompt/powershell'
import { CClandZshGenerator } from './sections/ccland/zsh'
import { CClandBashGenerator } from './sections/ccland/bash'
import { CClandPowerShellGenerator } from './sections/ccland/powershell'

/** Fixed generation order */
const SECTION_ORDER = ['variables', 'path', 'functions', 'aliases', 'prompt', 'ccland'] as const

type SectionName = (typeof SECTION_ORDER)[number]

/** Registry: sectionName -> shellType -> generator */
const registry = new Map<string, Map<ShellType, SectionGenerator>>()

function reg(gen: SectionGenerator): void {
  if (!registry.has(gen.sectionName)) registry.set(gen.sectionName, new Map())
  registry.get(gen.sectionName)!.set(gen.shellType, gen)
}

// Register all section generators
reg(new VariablesZshGenerator())
reg(new VariablesBashGenerator())
reg(new VariablesPowerShellGenerator())
reg(new PathZshGenerator())
reg(new PathBashGenerator())
reg(new PathPowerShellGenerator())
reg(new FunctionsZshGenerator())
reg(new FunctionsBashGenerator())
reg(new FunctionsPowerShellGenerator())
reg(new AliasesZshGenerator())
reg(new AliasesBashGenerator())
reg(new AliasesPowerShellGenerator())
reg(new PromptZshGenerator())
reg(new PromptBashGenerator())
reg(new PromptPowerShellGenerator())
reg(new CClandZshGenerator())
reg(new CClandBashGenerator())
reg(new CClandPowerShellGenerator())

function getSection(name: string, shellType: ShellType): SectionGenerator | undefined {
  return registry.get(name)?.get(shellType)
}

/** Shebang / header by shell type */
function generateHeader(shellType: ShellType, timestamp: string): string {
  const shebangs: Record<ShellType, string> = {
    zsh: '#!/bin/zsh',
    bash: '#!/bin/bash',
    powershell: '# PowerShell'
  }
  return [
    shebangs[shellType],
    '# ============================================',
    '# CCland Shell Configuration',
    `# Generated: ${timestamp}`,
    `# Shell: ${shellType}`,
    '# WARNING: This file is auto-generated by CCland.',
    '# Do not edit manually - changes will be overwritten.',
    '# ============================================',
    ''
  ].join('\n')
}

/** Map section name to data from shell config / cc config */
function getSectionData(
  name: SectionName,
  shellConfig: ShellConfigData,
  cclandData: CClandSectionData
): unknown {
  switch (name) {
    case 'variables': return shellConfig.variables
    case 'path': return shellConfig.pathEntries
    case 'functions': return shellConfig.functions
    case 'aliases': return shellConfig.aliases
    case 'prompt': return shellConfig.prompt
    case 'ccland': return cclandData
  }
}

/**
 * Generate a complete shell configuration file.
 * Assembles all sections in fixed order: header -> variables -> path -> functions -> aliases -> prompt -> ccland.
 */
export function generateFullConfig(
  shellType: ShellType,
  shellConfig: ShellConfigData,
  ccConfig: CCLaunchData,
  decryptedTokens: Map<string, string>,
  ctx: GenerateContext
): string {
  const cclandData: CClandSectionData = { ccConfig, decryptedTokens }
  const parts: string[] = [generateHeader(shellType, ctx.timestamp)]

  for (const sectionName of SECTION_ORDER) {
    const gen = getSection(sectionName, shellType)
    if (!gen) continue

    const data = getSectionData(sectionName, shellConfig, cclandData)
    const output = gen.generate(data, ctx)
    if (output) {
      parts.push(output)
    }
  }

  parts.push('') // trailing newline
  return parts.join('\n\n')
}
