import type { ShellType } from '@shared/shell'
import type { SectionGenerator } from './section-types'
import type { GenerateContext } from './section-types'
import type { ShellConfigData } from '@shared/shell-types'
import type { CCLaunchData, CXLandData } from '@shared/types'

import type { CCLandSectionData } from './sections/ccland/zsh'
import type { CXLandSectionData } from './sections/cxland/zsh'

// Section generators
import { VariablesZshGenerator } from './sections/variables/zsh'
import { VariablesBashGenerator } from './sections/variables/bash'
import { VariablesPowerShellGenerator } from './sections/variables/powershell'
import { PathZshGenerator } from './sections/path/zsh'
import { PathBashGenerator } from './sections/path/bash'
import { PathPowerShellGenerator } from './sections/path/powershell'
import { FunctionsZshGenerator } from './sections/functions/zsh'
import { FunctionsBashGenerator } from './sections/functions/bash'
import { FunctionsPowerShellGenerator } from './sections/functions/powershell'
import { AliasesZshGenerator } from './sections/aliases/zsh'
import { AliasesBashGenerator } from './sections/aliases/bash'
import { AliasesPowerShellGenerator } from './sections/aliases/powershell'
import { CCLandZshGenerator } from './sections/ccland/zsh'
import { CCLandBashGenerator } from './sections/ccland/bash'
import { CCLandPowerShellGenerator } from './sections/ccland/powershell'
import { CXLandZshGenerator } from './sections/cxland/zsh'
import { CXLandBashGenerator } from './sections/cxland/bash'
import { CXLandPowerShellGenerator } from './sections/cxland/powershell'
import { SystemProxyZshGenerator } from './sections/system-proxy/zsh'
import { SystemProxyBashGenerator } from './sections/system-proxy/bash'
import { SystemProxyPowerShellGenerator } from './sections/system-proxy/powershell'

/** Fixed generation order */
const SECTION_ORDER = ['variables', 'path', 'functions', 'aliases', 'systemProxy', 'ccland', 'cxland'] as const

type SectionName = (typeof SECTION_ORDER)[number]

/** Registry: sectionName -> shellType -> generator */
const registry = new Map<string, Map<ShellType, SectionGenerator>>()

function reg(gen: SectionGenerator): void {
  if (!registry.has(gen.sectionName)) registry.set(gen.sectionName, new Map())
  registry.get(gen.sectionName)!.set(gen.shellType, gen)
}

// Register all section generators
reg(new VariablesZshGenerator())
reg(new VariablesBashGenerator())
reg(new VariablesPowerShellGenerator())
reg(new PathZshGenerator())
reg(new PathBashGenerator())
reg(new PathPowerShellGenerator())
reg(new FunctionsZshGenerator())
reg(new FunctionsBashGenerator())
reg(new FunctionsPowerShellGenerator())
reg(new AliasesZshGenerator())
reg(new AliasesBashGenerator())
reg(new AliasesPowerShellGenerator())
reg(new CCLandZshGenerator())
reg(new CCLandBashGenerator())
reg(new CCLandPowerShellGenerator())
reg(new CXLandZshGenerator())
reg(new CXLandBashGenerator())
reg(new CXLandPowerShellGenerator())
reg(new SystemProxyZshGenerator())
reg(new SystemProxyBashGenerator())
reg(new SystemProxyPowerShellGenerator())

function getSection(name: string, shellType: ShellType): SectionGenerator | undefined {
  return registry.get(name)?.get(shellType)
}

/** Shebang / header by shell type */
function generateHeader(shellType: ShellType): string {
  const shebangs: Record<ShellType, string> = {
    zsh: '#!/bin/zsh',
    bash: '#!/bin/bash',
    powershell: '# PowerShell'
  }
  return [
    shebangs[shellType],
    '# Auto-generated by RCLand. Do not edit manually.',
    ''
  ].join('\n')
}

/** Map section name to data from shell config / cc config */
function getSectionData(
  name: SectionName,
  shellConfig: ShellConfigData,
  cclandData: CCLandSectionData,
  cxlandData: CXLandData,
  decryptedTokens: Map<string, string>
): unknown {
  switch (name) {
    case 'variables': return shellConfig.variables
    case 'path': return shellConfig.pathEntries
    case 'functions': return shellConfig.functions
    case 'aliases': return shellConfig.aliases
    case 'systemProxy': return undefined
    case 'ccland': return cclandData
    case 'cxland': {
      const result: CXLandSectionData = {
        cxConfig: cxlandData,
        decryptedTokens,
      }
      return result
    }
  }
}

/**
 * Generate a complete shell configuration file.
 * Assembles all sections in fixed order: header -> variables -> path -> functions -> aliases -> rcland.
 */
export function generateFullConfig(
  shellType: ShellType,
  shellConfig: ShellConfigData,
  ccConfig: CCLaunchData,
  cxConfig: CXLandData,
  decryptedTokens: Map<string, string>,
  ctx: GenerateContext
): string {
  const cclandData: CCLandSectionData = {
    ccConfig,
    decryptedTokens,
  }
  const parts: string[] = [generateHeader(shellType)]

  for (const sectionName of SECTION_ORDER) {
    const gen = getSection(sectionName, shellType)
    if (!gen) continue

    const data = getSectionData(sectionName, shellConfig, cclandData, cxConfig, decryptedTokens)
    const output = gen.generate(data, ctx)
    if (output) {
      parts.push(output)
    }
  }

  parts.push('') // trailing newline
  return parts.join('\n\n')
}
